blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.Home,name="home"),
    path("about/",views.About.as_view(),name="about"),
    path("contactpage/",views.Contact,name="contact"),
    path("dashboard/",views.dashboard,name="dashboard"),
    path("logout/",views.user_logout,name="logout"),
    path("signup/",views.user_signup,name="signup"),
    path("login/",views.user_login,name='login'),
    path("addpost/",views.AddPost,name='addpost'),
    path('updatePost/<int:id>/',views.UpdatePost, name='updatepost'),
    path('Delete/<int:id>',views.DeletPost, name='deletepost')
]

miniblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("blog.urls"))
]

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title=models.CharField(max_length=100)
    desc=models.TextField()

    def __str__(self):
        return f"{self.title}"
        
class Contact(models.Model):
    name=models.CharField(max_length=30)
    email=models.EmailField()
    address=models.CharField(max_length=1000)
    msg=models.CharField(max_length=400)

    def __str__(self):
        return f"massage from {self.name}"

blog/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from .models import Post
from django.forms import widgets
from django.forms.forms import Form
from django.forms.widgets import Textarea, Widget
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext,gettext_lazy as _

class ContactForm(forms.Form):
    user_name=forms.CharField(max_length=100,label="Name",widget=forms.TextInput(attrs={'class':'form-control'}))
    user_email=forms.EmailField(label="Email",widget=forms.EmailInput(attrs={'class':'form-control'}))
    user_address=forms.CharField(max_length=300,label="Address",widget=forms.TextInput(attrs={'class':'form-control'}))
    user_msg=forms.CharField(label='Massage',widget=forms.TextInput(attrs={'class':'form-control'}))

class SignupForm(UserCreationForm):
    password1=forms.CharField(label="Password" ,widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label="Confirm Password",widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model=User
        fields=("username","first_name","last_name","email")
        labels={
            'username':"UserName",'first_name':"First Name",'last_name':"Last Name",'email':"Email"}
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'})
        }

class LoginForm(AuthenticationForm):
    username=UsernameField(widget=forms.TextInput(attrs={"autofocus":True,'class':'form-control'}))
    password=forms.CharField(label="Password",widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}))

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','desc']
        labels={'title':'Title','desc':'Description'}
        widgets={
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'desc':forms.Textarea(attrs={'class':'form-control'})

        }

miniblog/blog/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from .models import Post
from django.forms import widgets
from django.forms.forms import Form
from django.forms.widgets import Textarea, Widget
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext,gettext_lazy as _

class ContactForm(forms.Form):
    user_name=forms.CharField(max_length=100,label="Name",widget=forms.TextInput(attrs={'class':'form-control'}))
    user_email=forms.EmailField(label="Email",widget=forms.EmailInput(attrs={'class':'form-control'}))
    user_address=forms.CharField(max_length=300,label="Address",widget=forms.TextInput(attrs={'class':'form-control'}))
    user_msg=forms.CharField(label='Massage',widget=forms.TextInput(attrs={'class':'form-control'}))

class SignupForm(UserCreationForm):
    password1=forms.CharField(label="Password" ,widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label="Confirm Password",widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model=User
        fields=("username","first_name","last_name","email")
        labels={
            'username':"UserName",'first_name':"First Name",'last_name':"Last Name",'email':"Email"}
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'})
        }

class LoginForm(AuthenticationForm):
    username=UsernameField(widget=forms.TextInput(attrs={"autofocus":True,'class':'form-control'}))
    password=forms.CharField(label="Password",widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}))

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','desc']
        labels={'title':'Title','desc':'Description'}
        widgets={
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'desc':forms.Textarea(attrs={'class':'form-control'})

        }

blog/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic.base import TemplateView, View
from django.views.generic.edit import FormView
from .forms import ContactForm, SignupForm,LoginForm,PostForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate,logout, login
from .models import Post,Contact
from django.contrib.auth.models import Group

# Create your views here.

def Home(request):
    posts=Post.objects.all()
    return render(request,'blog/home.html',{
        "posts":posts
    })



class About(TemplateView):
    template_name="blog/about.html"

# class Contact(FormView):
#     form_class=ContactForm
#     template_name="blog/contact-us.html"
#     success_url="/contactpage"

def Contact(request):
    if request.method=="POST":
        form=ContactForm(request.POST)
        if form.is_valid():
            uname=form.cleaned_data['user_name']
            uemail=form.cleaned_data['user_email']
            uaddress=form.cleaned_data['user_address']
            umsg=form.cleaned_data['user_msg']
            messages.success(request,'You Msg has been Sent')
            
                
    else:
        form=ContactForm()

        # messages.success(request,'You Email has been sent to the admin')
    return render(request,'blog/contact-us.html',{
        'form':form
            
    })





def dashboard(request):
    if request.user.is_authenticated:
        posts=Post.objects.all()
        return render(request,"blog/dashboard.html",{
            'posts':posts
        })
    else:
        return HttpResponseRedirect('/login')
    

def user_logout(request):
    logout(request)
    messages.success(request,"Logged out succesfully")
    return HttpResponseRedirect('/')

def user_signup(request):
    if request.method=="POST":
        form=SignupForm(request.POST)
        if form.is_valid():
            messages.success(request,"You become an Author")
            form.save()
            # group=Group.objects.get(name="author")
            # user.group.add(group)
    else:
        form=SignupForm()
    return render(request,"blog/sign-up.html",{
        "form":form
    })

def user_login(request):
    if not request.user.is_authenticated:
        if request.method=="POST":
            form=LoginForm(request=request,data=request.POST)
            if form.is_valid():
                uname=form.cleaned_data['username']
                upass=form.cleaned_data['password']
                user=authenticate(username=uname,password=upass)
                if user is not None:
                    login(request,user)
                    messages.success(request,'Logged In')
                    return HttpResponseRedirect('/dashboard')
            else:
                messages.warning(request,'Please check your username And password')
        else:
            form=LoginForm()
            
        return render(request,"blog/login.html",{
            "form":form
        })
    else :
        return HttpResponseRedirect('/dashboard')

def AddPost(request):
    if request.user.is_authenticated:
        if request.method=='POST':
            form=PostForm(request.POST)
            if form.is_valid():
                title=form.cleaned_data['title']
                desc=form.cleaned_data['desc']
                pst=Post(title=title,desc=desc)
                # pst.save()
                pst.save()
                form=PostForm()
        else:
            form=PostForm()
        return render(request,'blog/addpost.html',{
            'form':form
        })

def UpdatePost(request,id):

    if request.user.is_authenticated:
        if request.method=='POST':
            pi=Post.objects.get(pk=id)
            form=PostForm(request.POST,instance=pi)
            if form.is_valid():
                form.save()
        else:
            pi=Post.objects.get(pk=id)
            form=PostForm(instance=pi)

        return render(request,'blog/edit.html',{
                       'form':form
        })
    else:
        return HttpResponseRedirect('/login')

def DeletPost(request, id):
    if request.user.is_authenticated:
        if request.method=='POST':
            pi=Post.objects.get(pk=id)
            pi.delete()
            return HttpResponseRedirect('/dashboard')
        else:
            return HttpResponseRedirect('/login')

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
AboutUs
{% endblock title %}
{% block aboutactive %}{% endblock aboutactive %}
{% block css_style %}
<link rel="stylesheet" href="{% static 'blog/css/about.css' %}">
{%  endblock %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    
    <div class="col-sm-10 blog1"><h2 class="display-8 ">About Page</h2>
        <div class="jumbotron jumbotron-fluid">
          <div class="container">
            <p class="lead">
            Lorem ipsum dolor sit amet, 
            consectetur adipisicing elit, 
            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            Lorem ipsum dolor sit amet, 
            consectetur adipisicing elit,           
            </p>
            <p class="lead lead2">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, ipsa maiores. Excepturi accusantium, minima, esse laboriosam facilis temporibus nobis voluptas ipsa delectus vero saepe iusto, facere eaque ducimus nostrum iste?</p>
          </div>
        </div>
        </div>
        
{% endblock content %}

blog/templates/blog/addpost.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
Login
{% endblock title %}
{% block css_style %}
<!-- <link rel="stylesheet" href="{% static 'blog/css/addpost.css' %}"> -->
<link rel="stylesheet" href="{% static 'blog/css/home.css' %}">
{%  endblock %}
{% block content %}
    
    <div class="col-sm-10 blog1 ">
    <h2 class="display-8 ">Add Post</h2>
    <form class="form-group" action="" method="POST" novalidate >
    {% csrf_token %}
   
    {% for fm in form  %}
    <div class="fm1">
    {{fm.label_tag}}</div> 
    <small class="fm2">
    {{fm}}
</small>
                 <small class="text-warning">
        {{fm.errors }}
        </small>
  {% endfor %}
  <button class="btn btn-success my-4">Add Post</button>
 <a class="btn btn-danger" href="{% url 'dashboard' %}">Cancel</a> 

    </form>
        </div>
{% endblock content %}

blog/templates/blog/base.html
<!DOCTYPE html>


{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Blog{% endblock title %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href={% static 'blog/css/style.css' %}>
    {% block css_style %}{% endblock css_style %}
</head>
<body>

    {% include 'blog/navbar.html' %}
    <div class="content">
    {% block content %}{% endblock content %}

    </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

blog/templates/blog/contact-us.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
Contact Page
{% endblock title %}
{% block contactactive %}active{% endblock contactactive %}
{% block css_style %}
<link rel="stylesheet" href="{% static 'blog/css/home.css' %}">

{%  endblock %}
{% block content %}

<div class="col-sm-10 blog1">

    <form action="" method="POST" novalidate>
        <div class="form-contro">
            <h1 class="text-white">Contact Page</h1>
                    {% comment %} {% if messages %}
        {% for message in messages %}
        <p {% if message.tags %} class="alet alert-{{message.tags}}"{% endif %} >
        {{message}}
        </P>
        {% endfor %}
        {% endif %} {% endcomment %}
        {% csrf_token %}
        {{ form.user_name.label_tag }}
        {{ form.user_name }}
        <small class="text-danger">
        {{ form.user_name.errors }}
        </small>
        <div class="email">
        {{ form.user_email.label_tag }}
        {{ form.user_email }}
        <small class="text-danger">
        {{ form.user_email.errors }}
        </small>
    </div>
        <div class="address">
        {{form.user_address.label_tag}}
        {{form.user_address}}
                     <small class="text-danger">
        
            
        {{form.user_address.errors}}</small>
   
        </div>
        <div class="msg">
            {{form.user_msg.label_tag}}
            {{form.user_msg}}
             <small class="text-danger">
            {{form.user_msg.errors}}
            </small>
        </div>
        <button class="btn btn-primary my-3 text-white">Send</button>
        </div>

    </form>
 </div>
{% endblock content %}

blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
AboutUs
{% endblock title %}
{% block active %} active {% endblock %}
{% block css_style %}
<link rel="stylesheet" href="{% static 'blog/css/dashboard.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/home.css' %}">
{%  endblock %}
{% block content %}
    
    <div class="col-sm-10 blog1">
                            {% comment %} {% if messages %} {% endcomment %}
        {% for message in messages %}
        <h5 class="alert alert-success text-center " >
        {{message}}
        </h5>
        {% endfor %}
        {% comment %} {% endif %} {% endcomment %}
    <h2 class="display-8 ">Dashboard Page</h2> 
         
      <h4 class='text-center alert alert-info mt-5'>Show post information</h4>
    <a href="{% url 'addpost' %}" class="btn btn-success my-3">Add Post</a> 
     {% if posts %}
        <table class="table table-hover bg-white">
          <thead>
            <tr class="text-center">
              <th scope='col' style="width: 2%;">Id</th>
              <th scope='col' style="width: 28%;">Title</th>
              <th scope='col' style="width: 55% ;">Desc</th>
              <th scope='col' style="width: 15%;">Action</th>
            </tr>
          </thead>
            <tbody>
            {% for post in posts %}
            <tr>
                <td scope='row'>{{ post.id}}</td>
                <td>{{ post.title}}</td>
                <td>{{ post.desc}}</td>
                <td class="text-center">
                  <a href="{% url 'updatepost' post.id %}" class="btn btn-warning btn-sm" value="Upadate">Edit</a>
                  {% if perms.blog.delete_post%}
                  <form action="{% url 'deletepost' post.id %}" method="POST" class="d-inline">
                    {%csrf_token%}
                    <input  type="submit" value="Delete" class="btn btn-danger btn-sm">


                  </form>
                  {%endif%}
                </td>
              

            </tr>
            {%endfor%}
          </tbody>
       
        </table>
        {%endif%}
        </div>
  
{% endblock content %}

blog/templates/blog/edit.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
Update Post
{% endblock title %}
{% block css_style %}
<!-- <link rel="stylesheet" href="{% static 'blog/css/addpost.css' %}"> -->
<link rel="stylesheet" href="{% static 'blog/css/home.css' %}">
{%  endblock %}
{% block content %}
    
    <div class="col-sm-10 blog1 ">
    <h2 class="display-8 ">Update Post</h2>
    <form class="form-group" action="" method="POST" novalidate >
    {% csrf_token %}
   
    {% for fm in form  %}
    <div class="fm1">
    {{fm.label_tag}}</div> 
    <small class="fm2">
    {{fm}}
</small>
                 <!-- <small class="text-warning">
        {{fm.errors }}
        </small> -->
  {% endfor %}
  <button class="btn btn-success my-4">Upadate Post</button>
 <a class="btn btn-danger" href="{% url 'dashboard' %}">Cancel</a> 

    </form>
        </div>
{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}
{% block homeactive %} active {% endblock homeactive %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
{% block css_style %}
<link rel="stylesheet" href="{% static 'blog/css/home.css' %}">
{% endblock css_style %}
{% block content %}
<div class="col-sm-12 d-flex flex-column blog1">
        {% for message in messages %}
               <h5 class="alert alert-success text-center text-red" >
        {{message}}
        </h5>
        {% endfor %}

<h2 class='text-white my-5'>Home Page</h2>
{% for post in posts  %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4 ">{{post.title}}</h1>
    <p class="lead">
    {{post.desc}}
    </p>
  </div>
</div>
{% endfor %}
</div>
{% endblock content %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
Login
{% endblock title %}
{% block loginactive %}active{% endblock loginactive %}
{% block css_style %}
<link rel="stylesheet" href="{% static 'blog/css/login.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/home.css' %}">
{%  endblock %}
{% block content %}
    
    <div class="col-sm-10 blog1">
    <h2 class="display-8 ">login Page</h2>
            {% for message in messages %}
               <p class="alert alert-warning text-center text-red" >
        {{message}}
        </p>
        {% endfor %}

    <form action="" method="POST" novalidate>
    {% csrf_token %}
      {% for fm in form  %}
        {{fm.label_tag}}
        {{fm}}
                     {% comment %} <small class="text-warning">
            {{fm.errors }}
            </small> {% endcomment %}
      {% endfor %}
      <button class="btn btn-primary my-4">Submit</button>
    </form>
        </div>
{% endblock content %}

blog/templates/blog/navbar.html
{% comment %} {% extends 'blog/base.html' %} {% endcomment %}
{% load static %}

    <title>My blog</title>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">MiniBlog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link {% block active %}{% endblock %}" aria-current="page" href="{% url 'home' %}">Home</a>
        <a class="nav-link {% block asctive %}{% endblock %}" href="{% url 'about' %}">About</a>
        <a class="nav-link {% block contactactive %}{% endblock contactactive %}" href="{% url 'contact' %}">Contact</a>
        {% if request.user.is_authenticated %}
        <a class="nav-link {% block dashboardactive %}{% endblock dashboardactive %}" href="{% url 'dashboard' %}">Dashboard</a>
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a class="nav-link {% block signupactive %} {% endblock signupactive %}" href="{% url 'signup' %}">SignUp</a>
        <a class="nav-link {% block loginactive %}{% endblock loginactive %}" href="{% url 'login' %}">Login</a>
     {% endif %}
    </div>
  </div>
</nav>
    </div>
  </div>
</nav>

blog/templates/blog/sign-up.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
AboutUs
{% endblock title %}
{% block signupactive %} active {% endblock signupactive %}
{% block css_style %}
<link rel="stylesheet" href="{% static 'blog/css/sign.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/home.css' %}">
{%  endblock %}

{% block content %}

    
    <div class="col-sm-10 blog1">
        <h2 class="display-8 ">SignUp Page</h2>
        {% for message in messages %}
               <h5 class="alert alert-success text-center text-red" >
        {{message}}
        </h5>
        {% endfor %}
        <form action="" method="POST" novalidate>
            {% csrf_token %}
            {% for fm in form %}
        <div class="form-group">

            {{fm.label_tag}} {{fm}}
             <small class="text-danger">
            {{fm.errors }}
            </small>
        </div>
           
                {% endfor %}
            {% if form.non_field_errors%}
            {% for error in form.non_field_errors%}
            <p class="alert alert-warning my-3">{{error}}</p>
            {%endfor%}
            {% endif %}
            <button class="btn btn-primary">Submit</button>

        </form>
        </div>
    
{% endblock content %}